name: Set reviewer for v18
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "18.0"

jobs:
  pr18:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Assign reviewer and set auto merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        url: ${{ github.event.pull_request.html_url }}
      run: |
        gh pr edit "$url" --add-assignee fcharlaix-opendsi --add-reviewer fcharlaix-opendsi
        gh pr merge "$url" --merge --auto
