name: Set reviewer for v18
on:
  pull_request:
    types:
      - opened
    branches:
      - "18.0"

jobs:
  pr18:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: fcharlaix-opendsi
