name: Set reviewer for v18
on:
  pull_request:
    types:
      - opened
    branches:
      - "18.0"

jobs:
  pr18:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign reviewer and set auto merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-reviewer fcharlaix-opendsi
          gh pr merge "$url" --merge --auto
